name: Install and Start Apache

on: [push]  # Triggers the workflow on push events to the repository

jobs:
  build:
    runs-on: ubuntu-latest  # Specifies the runner environment

    steps:
    - uses: actions/checkout@v2  # Checks out your repository under $GITHUB_WORKSPACE

    - name: Update packages list
      run: sudo apt-get update
      
    - name: Install Apache
      run: sudo apt-get install -y apache2  # Installs Apache

    - name: Start Apache service
      run: sudo systemctl start apache2  # Starts the Apache service

    - name: Check Apache status
      run: sudo systemctl status apache2  # Optional: Check the status of the Apache service
